import { browserIconSvg } from "./browser-icons";
/** Static viewer: page strings only ever enter textContent or form values. */
export const viewerHtml = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Browse — live browser</title><style>
:root{color-scheme:dark;font:13px system-ui,sans-serif}*{box-sizing:border-box}html,body{width:100%;height:100%;margin:0;overflow:hidden}body{display:flex;flex-direction:column;background:#0b0b0d;color:#d4d4d8}header{height:48px;flex:none;display:flex;gap:4px;padding:7px 10px;align-items:center;border-bottom:1px solid #ffffff12;background:#111113}body.embedded header{padding-right:50px}button,summary{display:grid;place-items:center;width:32px;height:32px;border:0;border-radius:6px;background:transparent;color:#a1a1aa;cursor:pointer;flex:none}button:hover,summary:hover{background:#ffffff0c;color:#fafafa}button:focus-visible,summary:focus-visible,input:focus-visible{outline:2px solid #71717a;outline-offset:1px}svg{width:17px;height:17px;fill:none;stroke:currentColor;stroke-width:1.7;stroke-linecap:round;stroke-linejoin:round}input{flex:1;min-width:0;height:32px;margin:0 5px;padding:0 10px;border:1px solid transparent;border-radius:6px;background:#ffffff05;color:#e4e4e7;font:inherit}input:focus{background:#ffffff09}input::placeholder{color:#71717a}main{position:relative;display:grid;place-items:center;flex:1;min-height:0;min-width:0;overflow:hidden;padding:12px}#screen{display:block;flex:none;outline-offset:2px;box-shadow:0 6px 32px #0005;border-radius:2px}#screen:not([src]){visibility:hidden}#status,#machine{position:absolute;bottom:8px;max-width:calc(50% - 20px);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;padding:4px 8px;border-radius:5px;background:#111113dd;color:#a1a1aa;font-size:11px;pointer-events:none}#status{left:14px}#machine{right:14px}details{position:relative}summary{list-style:none}summary::-webkit-details-marker{display:none}.menu{position:absolute;z-index:5;right:0;top:38px;width:260px;padding:10px;border:1px solid #ffffff18;border-radius:10px;background:#18181b;box-shadow:0 12px 30px #0008}.menu button{width:100%;display:block;text-align:left;padding:0 8px;color:#e4e4e7}#identity{padding:8px;color:#a1a1aa;overflow-wrap:anywhere;font-size:12px;line-height:1.6}@media(max-width:420px){header{padding-left:4px;gap:0}main{padding:6px}input{margin:0 2px;padding:0 6px}}
</style></head><body>
<header aria-label="Browser navigation">
<button id="back" title="Back" aria-label="Back">${browserIconSvg("ArrowLeft")} </button>
<button id="forward" title="Forward" aria-label="Forward">${browserIconSvg("ArrowRight")} </button>
<button id="reload" title="Reload page" aria-label="Reload page">${browserIconSvg("RefreshCw")} </button>
<input id="url" aria-label="Page address" placeholder="Enter URL" spellcheck="false" autocapitalize="off">
<button id="go" title="Go" aria-label="Go">${browserIconSvg("ArrowRight")} </button>
<details><summary title="Browser options" aria-label="Browser options">${browserIconSvg("More")}</summary><div class="menu"><button id="pause">Pause view</button><div id="identity">Loading session details…</div></div></details>
</header>
<main id="viewport"><img id="screen" tabindex="0" aria-label="Live browser; click to interact, type or paste, scroll, and use navigation keys"><div id="status" role="status">Connecting…</div><div id="machine" aria-label="Browser machine"></div></main>
<script>
if(new URL(location.href).searchParams.has('embedded'))document.body.classList.add('embedded');
const id=new URL(location.href).searchParams.get('id');const screen=document.querySelector('#screen'),status=document.querySelector('#status'),address=document.querySelector('#url');
let paused=false,acting=false,closed=false,vw=1280,vh=800,seq=0,cast=null,lastFrame=0,lastSocketFrame=0,inViewport=false;const clientId=crypto.randomUUID();const queue=[];
async function json(url,options){const r=await fetch(url,{...options,cache:'no-store'});const data=await r.json();if(!r.ok||data.error)throw Error(data.error||r.statusText);return data;}
const viewport=document.querySelector('#viewport');function fit(){const style=getComputedStyle(viewport);const w=viewport.clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight),h=viewport.clientHeight-parseFloat(style.paddingTop)-parseFloat(style.paddingBottom);const scale=Math.max(0,Math.min(w/vw,h/vh,1));screen.style.width=vw*scale+'px';screen.style.height=vh*scale+'px';}new ResizeObserver(fit).observe(viewport);
function show(frame){if(!frame||!frame.data)return;vw=frame.width||vw;vh=frame.height||vh;seq=frame.seq||seq;fit();screen.src='data:image/jpeg;base64,'+frame.data;if(document.activeElement!==address&&frame.url)address.value=frame.url;if(!acting)status.textContent='Live · '+vw+' × '+vh;}
screen.onload=()=>{lastFrame=Date.now();};
new IntersectionObserver(entries=>{inViewport=entries.some(e=>e.isIntersecting&&e.intersectionRatio>0);void reportPresence();}).observe(screen);
async function reportPresence(){try{await json('./presence',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,clientId,visible:inViewport&&!closed&&!paused&&!document.hidden&&Date.now()-lastFrame<15000})});}catch{}}
void json('./viewer-info?id='+encodeURIComponent(id)).then(info=>{document.querySelector('#machine').textContent=info.hostLabel;document.querySelector('#identity').textContent='Machine: '+info.hostLabel+' · Session: '+info.id;}).catch(e=>{status.textContent=e.message;});
setInterval(reportPresence,4000);document.addEventListener('visibilitychange',reportPresence);
function point(e){const r=screen.getBoundingClientRect();return{x:Math.min(vw-1,Math.max(0,(e.clientX-r.left)*vw/r.width)),y:Math.min(vh-1,Math.max(0,(e.clientY-r.top)*vh/r.height))};}
function openCast(){if(closed||paused||cast)return;const ws=new WebSocket((location.protocol==='https:'?'wss:':'ws:')+'//'+location.host+location.pathname.replace(/\\/viewer$/,'/cast')+'?id='+encodeURIComponent(id));cast=ws;ws.onmessage=e=>{try{const f=JSON.parse(e.data);if(f.error){status.textContent=f.error;ws.close();}else{lastSocketFrame=Date.now();show(f);}}catch{}};ws.onclose=()=>{if(cast===ws)cast=null;if(!closed&&!paused)setTimeout(openCast,400);};ws.onerror=()=>ws.close();}
async function poll(){if(closed)return;try{if(!paused&&!document.hidden&&(!cast||Date.now()-lastSocketFrame>5000))show(await json('./frame?id='+encodeURIComponent(id)+'&after='+seq));}catch(e){status.textContent=e.message;}finally{if(!closed)setTimeout(poll,cast?2000:120);}}
function input(action){if(queue.length>=100){status.textContent='Input queue is full; wait for pending input.';return;}queue.push(action);if(!acting)void drain();}
async function drain(){if(!queue.length||closed)return;acting=true;const action=queue.shift();status.textContent='Working…';try{let job=await json('./input',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,input:action})});while(job.status==='running'){await new Promise(r=>setTimeout(r,300));job=await json('./viewer-job?id='+encodeURIComponent(id)+'&job='+encodeURIComponent(job.id));}if(job.status!=='succeeded')throw Error(job.error||job.status);status.textContent='Input completed';}catch(e){queue.length=0;status.textContent=e.message;}finally{acting=false;if(queue.length)void drain();}}
screen.addEventListener('click',e=>{screen.focus();const p=point(e);input({kind:'click',x:p.x,y:p.y});});
screen.addEventListener('wheel',e=>{e.preventDefault();input({kind:'scroll',deltaY:Math.max(-1600,Math.min(1600,e.deltaY))});},{passive:false});
screen.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;const keys=['Enter','Tab','Backspace','Escape','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Delete'];if(keys.includes(e.key)){e.preventDefault();input({kind:'key',key:e.key});}else if(e.key.length===1){e.preventDefault();input({kind:'text',text:e.key});}});
screen.addEventListener('paste',e=>{e.preventDefault();const text=e.clipboardData.getData('text/plain');if(text)input({kind:'text',text});});
for(const action of ['back','forward','reload'])document.querySelector('#'+action).onclick=()=>input({kind:'history',action});
document.querySelector('#go').onclick=()=>{try{const text=address.value.trim();const url=new URL(text.includes('://')?text:'https://'+text);if(!['http:','https:'].includes(url.protocol)||url.username||url.password)throw Error('Enter an HTTP or HTTPS address without login details.');input({kind:'navigate',url:url.href});}catch(e){status.textContent=e.message;}};address.onkeydown=e=>{if(e.key==='Enter')document.querySelector('#go').click();};
document.querySelector('#pause').onclick=e=>{paused=!paused;e.target.textContent=paused?'Resume view':'Pause view';if(paused){cast&&cast.close();cast=null;status.textContent='View paused; browser remains active';}else{status.textContent='Resuming…';openCast();}};
window.addEventListener('pagehide',()=>{closed=true;cast&&cast.close();void reportPresence();});openCast();poll();
</script></body></html>`;
