/** Static viewer: page strings only ever enter textContent or form values. */
export const viewerHtml = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Browse — live browser</title><style>
:root{color-scheme:dark;font:14px system-ui}body{margin:0;background:#18181b;color:#eee}header{display:flex;gap:8px;padding:12px;align-items:center}input{flex:1;min-width:0}input,button{font:inherit;padding:8px;border:1px solid #555;border-radius:6px;background:#27272a;color:inherit}button{cursor:pointer}#screen{display:block;width:min(100%,1280px);height:auto;margin:auto;outline-offset:-3px}#status{padding:0 12px 10px;min-height:20px}#note{padding:10px 12px;color:#aaa;font-size:12px}</style></head><body>
<header><b>Browse</b><input id="url" aria-label="Page address" placeholder="https://example.com"><button id="go">Go</button><button id="pause">Pause view</button></header>
<div id="status" role="status">Connecting…</div><img id="screen" tabindex="0" aria-label="Live browser; click to interact, type or paste, scroll, and use navigation keys"><div id="note">Live screencast from headed Chrome on the thread host. Click the page to type or paste. Use the agent for dragging, file uploads, and downloads.</div>
<script>
const id=new URL(location.href).searchParams.get('id');const screen=document.querySelector('#screen'),status=document.querySelector('#status'),address=document.querySelector('#url');
let paused=false,acting=false,closed=false,vw=1280,vh=800,seq=0,cast=null;const queue=[];
async function json(url,options){const r=await fetch(url,{...options,cache:'no-store'});const data=await r.json();if(!r.ok||data.error)throw Error(data.error||r.statusText);return data;}
function show(frame){if(!frame||!frame.data)return;vw=frame.width||vw;vh=frame.height||vh;seq=frame.seq||seq;screen.src='data:image/jpeg;base64,'+frame.data;if(document.activeElement!==address&&frame.url)address.value=frame.url;if(!acting)status.textContent='Live · '+vw+' × '+vh+' · thread host';}
function point(e){const r=screen.getBoundingClientRect();return{x:Math.min(vw-1,Math.max(0,(e.clientX-r.left)*vw/r.width)),y:Math.min(vh-1,Math.max(0,(e.clientY-r.top)*vh/r.height))};}
function openCast(){if(closed||paused||cast)return;const ws=new WebSocket((location.protocol==='https:'?'wss:':'ws:')+'//'+location.host+location.pathname.replace(/\\/viewer$/,'/cast')+'?id='+encodeURIComponent(id));cast=ws;ws.onmessage=e=>{try{const f=JSON.parse(e.data);if(f.error)status.textContent=f.error;else show(f);}catch{}};ws.onclose=()=>{if(cast===ws)cast=null;if(!closed&&!paused)setTimeout(openCast,400);};ws.onerror=()=>ws.close();}
async function poll(){if(closed)return;try{if(!paused&&!cast&&!document.hidden)show(await json('./frame?id='+encodeURIComponent(id)+'&after='+seq));}catch(e){status.textContent=e.message;}finally{if(!closed)setTimeout(poll,cast?2000:120);}}
function input(action){if(queue.length>=100){status.textContent='Input queue is full; wait for pending input.';return;}queue.push(action);if(!acting)void drain();}
async function drain(){if(!queue.length||closed)return;acting=true;const action=queue.shift();status.textContent='Working…';try{let job=await json('./input',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,input:action})});while(job.status==='running'){await new Promise(r=>setTimeout(r,300));job=await json('./viewer-job?id='+encodeURIComponent(id)+'&job='+encodeURIComponent(job.id));}if(job.status!=='succeeded')throw Error(job.error||job.status);status.textContent='Input completed';}catch(e){queue.length=0;status.textContent=e.message;}finally{acting=false;if(queue.length)void drain();}}
screen.addEventListener('click',e=>{screen.focus();const p=point(e);input({kind:'click',x:p.x,y:p.y});});
screen.addEventListener('wheel',e=>{e.preventDefault();input({kind:'scroll',deltaY:Math.max(-1600,Math.min(1600,e.deltaY))});},{passive:false});
screen.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;const keys=['Enter','Tab','Backspace','Escape','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Delete'];if(keys.includes(e.key)){e.preventDefault();input({kind:'key',key:e.key});}else if(e.key.length===1){e.preventDefault();input({kind:'text',text:e.key});}});
screen.addEventListener('paste',e=>{e.preventDefault();const text=e.clipboardData.getData('text/plain');if(text)input({kind:'text',text});});
document.querySelector('#go').onclick=()=>input({kind:'navigate',url:address.value});address.onkeydown=e=>{if(e.key==='Enter')document.querySelector('#go').click();};
document.querySelector('#pause').onclick=e=>{paused=!paused;e.target.textContent=paused?'Resume view':'Pause view';if(paused){cast&&cast.close();cast=null;status.textContent='View paused; browser remains active';}else{status.textContent='Resuming…';openCast();}};
window.addEventListener('pagehide',()=>{closed=true;cast&&cast.close();});openCast();poll();
</script></body></html>`;
