// Disposable fixture only. Measures synthetic viewer click -> displayed pixel.
import fs from 'node:fs/promises';import WebSocket from 'ws';import assert from 'node:assert/strict';
const [profile,port='39115']=process.argv.slice(2);assert.match(profile??'',/^ab-[a-f0-9-]+$/);assert.match(port,/^[0-9]{1,5}$/);
const sourcePort=(await fs.readFile(`${process.env.HOME}/.bb/plugins/browse/host-data/profiles/${profile}/DevToolsActivePort`,'utf8')).split('\n')[0];
async function connect(port,predicate){const list=await(await fetch(`http://127.0.0.1:${port}/json/list`)).json();const target=list.find(predicate);assert.ok(target);const ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise(r=>ws.once('open',r));let id=0;const pending=new Map();ws.on('message',raw=>{const m=JSON.parse(String(raw));if(pending.has(m.id)){pending.get(m.id)(m);pending.delete(m.id);}});return{ws,eval:async expression=>{const seq=++id;const p=new Promise(r=>pending.set(seq,r));ws.send(JSON.stringify({id:seq,method:'Runtime.evaluate',params:{expression,returnByValue:true,awaitPromise:true}}));const m=await p;if(m.error||m.result.exceptionDetails)throw Error(JSON.stringify(m.error||m.result.exceptionDetails));return m.result.result.value;}};}
const source=await connect(sourcePort,t=>t.url==='http://127.0.0.1:39114/'),viewer=await connect(port,t=>t.type==='page'&&t.url.startsWith('http://127.0.0.1:38886/api/v1/plugins/browse/http/viewer?'));
const timeout=setTimeout(()=>{console.error('latency fixture timed out');source.ws.close();viewer.ws.close();process.exitCode=1;},30000);
try{
 const point=await source.eval(`(()=>{const signal=document.createElement('div');signal.id='latency-signal';Object.assign(signal.style,{position:'fixed',left:'0',top:'0',width:'30px',height:'30px',background:'rgb(0,0,255)',zIndex:'9999',pointerEvents:'none'});document.body.append(signal);let count=0;document.querySelector('#count').addEventListener('click',()=>{signal.style.background=++count%2?'rgb(255,0,0)':'rgb(0,255,0)'});const r=document.querySelector('#count').getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2};})()`);
 const times=await viewer.eval(`(async()=>{const times=[];for(let i=0;i<30;i++){while(inflight||directQueue.length)await new Promise(r=>setTimeout(r,10));const r=screen.getBoundingClientRect(),start=performance.now();for(const type of ['pointerdown','pointerup'])screen.dispatchEvent(new PointerEvent(type,{bubbles:true,cancelable:true,isPrimary:true,pointerId:1,pointerType:'mouse',button:0,buttons:type==='pointerdown'?1:0,clientX:r.left+${point.x}*r.width/vw,clientY:r.top+${point.y}*r.height/vh}));while(true){await new Promise(requestAnimationFrame);const pixel=paint.getImageData(Math.floor(12*screen.width/vw),Math.floor(12*screen.height/vh),1,1).data;const channel=i%2===0?0:1;if(pixel[channel]>200&&pixel[2]<50){times.push(performance.now()-start);break;}if(performance.now()-start>2000)throw Error('Visual update timeout');}await new Promise(r=>setTimeout(r,100));}return times;})()`);
 const sorted=[...times].sort((a,b)=>a-b);console.log(JSON.stringify({test:'click-to-displayed-pixel',scope:'local synthetic viewer input, no WAN or OS dispatch delay',samples:times,p50:sorted[14],p95:sorted[28],max:sorted.at(-1)}));
}finally{clearTimeout(timeout);source.ws.close();viewer.ws.close();}
