import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {writeFileSync} from 'node:fs';
import {RiSettings3Line,RiBrain3Line,RiContrast2Line,RiKeyboardLine,RiGlobalLine,RiBarChartLine,RiFileTextLine,RiFolderLine,RiInstanceLine,RiDownloadLine,RiStore2Line,RiFlaskLine,RiChat1Line,RiArchiveLine} from '@remixicon/react';
const icons={Settings:RiSettings3Line,Bot:RiBrain3Line,Palette:RiContrast2Line,SlidersHorizontal:RiKeyboardLine,Browser:RiGlobalLine,ChartColumn:RiBarChartLine,File:RiFileTextLine,FolderGit:RiFolderLine,Laptop:RiInstanceLine,PackageReceive:RiDownloadLine,Puzzle:RiStore2Line,Beaker:RiFlaskLine,MessageSquare:RiChat1Line,Archive:RiArchiveLine};
const scope='[data-testid="settings-sidebar-body"]';
let css='/* Remix artwork scoped to native Settings navigation. Generated by scripts/settings-icons.mjs. */\n';
for(const [name,Icon] of Object.entries(icons)){
 const svg=renderToStaticMarkup(createElement(Icon));
 css+=`${scope} [data-icon="${name}"] { --silk-settings-icon: url("data:image/svg+xml,${encodeURIComponent(svg)}"); }\n`;
}
css+=`${scope} a [data-icon] { width:16px; height:16px; min-width:16px; min-height:16px; }\n`;
const names=Object.keys(icons).map(n=>`[data-icon="${n}"]`).join(',');
css+=`${scope} :is(${names}) { background-color:currentColor; mask:var(--silk-settings-icon) center / contain no-repeat; }\n${scope} :is(${names}) > svg { opacity:0; }\n`;
writeFileSync('lib/settings-icons.css',css);
