/** Static viewer: page strings only ever enter textContent or form values. */
export const viewerHtml = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Browse — live browser</title><style>
:root{color-scheme:dark;font:14px system-ui}body{margin:0;background:#18181b;color:#eee}header{display:flex;gap:8px;padding:12px;align-items:center}input{flex:1;min-width:0}input,button{font:inherit;padding:8px;border:1px solid #555;border-radius:6px;background:#27272a;color:inherit}button{cursor:pointer}#screen{display:block;width:min(100%,1280px);height:auto;margin:auto;outline-offset:-3px}#status{padding:0 12px 10px;min-height:20px}#note{padding:10px 12px;color:#aaa;font-size:12px}</style></head><body>
<header><b>Browse</b><input id="url" aria-label="Page address" placeholder="https://example.com"><button id="go">Go</button><button id="pause">Pause view</button></header>
<div id="status" role="status">Connecting…</div><img id="screen" tabindex="0" aria-label="Live browser; click to interact, type or paste, scroll, and use navigation keys"><div id="note">Runs on the thread’s host. Click the page to type or paste. The viewer refreshes while visible; automation continues when this viewer is closed. Use the agent for dragging, file uploads, and downloads.</div>
<script>
const id=new URL(location.href).searchParams.get('id');const screen=document.querySelector('#screen'),status=document.querySelector('#status'),address=document.querySelector('#url');
let paused=false,acting=false,closed=false;const queue=[];
async function json(url,options){const r=await fetch(url,{...options,cache:'no-store'});const data=await r.json();if(!r.ok||data.error)throw Error(data.error||r.statusText);return data;}
async function refresh(){if(closed)return;try{if(!paused&&!document.hidden){const frame=await json('./frame?id='+encodeURIComponent(id));screen.src='data:image/jpeg;base64,'+frame.data;if(document.activeElement!==address)address.value=frame.url;if(!acting)status.textContent='Live · 1280 × 800 · thread host';}}catch(e){status.textContent=e.message;}finally{if(!closed)setTimeout(refresh,800);}}
function input(action){if(queue.length>=100){status.textContent='Input queue is full; wait for pending input.';return;}queue.push(action);if(!acting)void drain();}
async function drain(){if(!queue.length||closed)return;acting=true;const action=queue.shift();status.textContent='Working…';try{let job=await json('./input',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,input:action})});while(job.status==='running'){await new Promise(r=>setTimeout(r,300));job=await json('./viewer-job?id='+encodeURIComponent(id)+'&job='+encodeURIComponent(job.id));}if(job.status!=='succeeded')throw Error(job.error||job.status);status.textContent='Input completed';}catch(e){queue.length=0;status.textContent=e.message;}finally{acting=false;if(queue.length)void drain();}}
screen.addEventListener('click',e=>{screen.focus();const r=screen.getBoundingClientRect();input({kind:'click',x:Math.min(1279,Math.max(0,(e.clientX-r.left)*1280/r.width)),y:Math.min(799,Math.max(0,(e.clientY-r.top)*800/r.height))});});
screen.addEventListener('wheel',e=>{e.preventDefault();input({kind:'scroll',deltaY:Math.max(-1600,Math.min(1600,e.deltaY))});},{passive:false});
screen.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;const keys=['Enter','Tab','Backspace','Escape','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Delete'];if(keys.includes(e.key)){e.preventDefault();input({kind:'key',key:e.key});}else if(e.key.length===1){e.preventDefault();input({kind:'text',text:e.key});}});
screen.addEventListener('paste',e=>{e.preventDefault();const text=e.clipboardData.getData('text/plain');if(text)input({kind:'text',text});});
document.querySelector('#go').onclick=()=>input({kind:'navigate',url:address.value});address.onkeydown=e=>{if(e.key==='Enter')document.querySelector('#go').click();};
document.querySelector('#pause').onclick=e=>{paused=!paused;e.target.textContent=paused?'Resume view':'Pause view';status.textContent=paused?'View paused; browser remains active':'Resuming…';};
window.addEventListener('pagehide',()=>closed=true);refresh();
</script></body></html>`;
